package ventanas;

import Clases.DirectorioTelefonico;

/**
 *
 * @author Usuario
 */
public class Escritorio extends javax.swing.JFrame {
    private static DirectorioTelefonico directorio=new DirectorioTelefonico();
    
    public Escritorio() {
        super("Directorio Telefonico"); ///TITULO VENTANA
        initComponents();
    }

    public static DirectorioTelefonico getDirectorio() {
        return directorio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorio = new javax.swing.JDesktopPane();
        jMenu = new javax.swing.JMenuBar();
        jMCliente = new javax.swing.JMenu();
        jMIAgregarCliente = new javax.swing.JMenuItem();
        jMIBuscarCliente = new javax.swing.JMenuItem();
        jMIBorrarCliente = new javax.swing.JMenuItem();
        jMIBuscarApellido = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        jMCliente.setText("Administrar Clientes");

        jMIAgregarCliente.setText("Agregar Cliente");
        jMIAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarClienteActionPerformed(evt);
            }
        });
        jMCliente.add(jMIAgregarCliente);

        jMIBuscarCliente.setText("Buscar Telefono");
        jMIBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBuscarClienteActionPerformed(evt);
            }
        });
        jMCliente.add(jMIBuscarCliente);

        jMIBorrarCliente.setText("Borrar Cliente");
        jMIBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBorrarClienteActionPerformed(evt);
            }
        });
        jMCliente.add(jMIBorrarCliente);

        jMIBuscarApellido.setText("Buscar Apellido");
        jMIBuscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBuscarApellidoActionPerformed(evt);
            }
        });
        jMCliente.add(jMIBuscarApellido);

        jMenuItem1.setText("Buscar Ciudad");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMCliente.add(jMenuItem1);

        jMenu.add(jMCliente);

        jMSalir.setText("Salir");

        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMSalir.add(jMISalir);

        jMenu.add(jMSalir);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ///------------ABRIR VENTANA AGREGAR CLIENTE------------
    private void jMIAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarClienteActionPerformed
        ///------------ESTOS COMENTARIOS SON PARA ENTENDER NOSE SI SERIAN LOS CORRECTOS------------
        jEscritorio.removeAll();///CIERRA VENTANAS
        jEscritorio.repaint();///PINTA FONDO
        VistaAgregarCliente vap=new VistaAgregarCliente();///CREAR VENTANA
        vap.setVisible(true);///VENTANA VISIBLE
        jEscritorio.add(vap);///MOSTRAR VENTANA
    }//GEN-LAST:event_jMIAgregarClienteActionPerformed

    
    ///------------ABRIR VENTANA BUSCAR CLIENTE------------
    private void jMIBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuscarClienteActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        VistaBuscarCliente vbc=new VistaBuscarCliente();
        vbc.setVisible(true);
        jEscritorio.add(vbc);
    }//GEN-LAST:event_jMIBuscarClienteActionPerformed

    ///------------MENU ITEM SALIR------------
    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        this.dispose(); ///CERRAR VENTANA
    }//GEN-LAST:event_jMISalirActionPerformed

    ///------------ABRIR VENTANA BORRAR CLIENTE------------
    private void jMIBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBorrarClienteActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        VistaBorrarCliente vBc=new VistaBorrarCliente();
        vBc.setVisible(true);
        jEscritorio.add(vBc);
    }//GEN-LAST:event_jMIBorrarClienteActionPerformed

    private void jMIBuscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuscarApellidoActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        VistaBuscarApellidos vBa=new VistaBuscarApellidos();
        vBa.setVisible(true);
        jEscritorio.add(vBa);
    }//GEN-LAST:event_jMIBuscarApellidoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        VistaBuscarCiudad vBc=new VistaBuscarCiudad();
        vBc.setVisible(true);
        jEscritorio.add(vBc);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenu jMCliente;
    private javax.swing.JMenuItem jMIAgregarCliente;
    private javax.swing.JMenuItem jMIBorrarCliente;
    private javax.swing.JMenuItem jMIBuscarApellido;
    private javax.swing.JMenuItem jMIBuscarCliente;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
