package ventanas;

import Clases.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VistaAgregarCliente extends javax.swing.JInternalFrame {
    
    
    public VistaAgregarCliente() {
        super("AGREGAR CLIENTE");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLDNI = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLCiudad = new javax.swing.JLabel();
        jLTelefono = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTCiudad = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLDireccion = new javax.swing.JLabel();
        jTDireccion = new javax.swing.JTextField();
        jTDNI = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();

        jLDNI.setText("DNI:");

        jLApellido.setText("APELLIDO:");

        jLNombre.setText("NOMBRE:");

        jLCiudad.setText("CIUDAD:");

        jLTelefono.setText("TELEFONO:");

        jTApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTApellidoKeyTyped(evt);
            }
        });

        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });

        jTCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCiudadKeyTyped(evt);
            }
        });

        jBGuardar.setText("GUARDAR");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBNuevo.setText("NUEVO");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLDireccion.setText("DIRECCION:");

        jTDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTDNIKeyTyped(evt);
            }
        });

        jTTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTTelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLApellido)
                    .addComponent(jLNombre)
                    .addComponent(jLCiudad)
                    .addComponent(jLTelefono)
                    .addComponent(jLDireccion)
                    .addComponent(jLDNI))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(jTApellido)
                            .addComponent(jTNombre)
                            .addComponent(jTCiudad)
                            .addComponent(jTDNI)
                            .addComponent(jTTelefono))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jBNuevo)
                        .addGap(31, 31, 31)
                        .addComponent(jBSalir)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBGuardar)
                    .addComponent(jBSalir))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ///------------BOTON GUARDAR CLIENTE------------
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        boolean msj=false;
        if(!msj){msj=verificarCamposnum(jTDNI);}
        if(!msj){msj=verificarCampos(jTApellido);}
        if(!msj){msj=verificarCampos(jTNombre);}
        if(!msj){msj=verificarCampos(jTCiudad);}
        if(!msj){msj=verificarCampos(jTDireccion);}
        if(!msj){msj=verificarCamposnum(jTTelefono);}
        if(!msj){
            msj=Escritorio.getDirectorio().agregarCliente(new Cliente(Integer.parseInt(jTDNI.getText()),jTNombre.getText(),jTApellido.getText(),jTCiudad.getText(),jTDireccion.getText(),Long.parseLong(jTTelefono.getText())));
            if (msj) {  ///SI EL CLIENTE NO ESTA REPETIDO SE GUARDA
                JOptionPane.showMessageDialog(this,"Datos guardados");
                limpiar();  ///LIMPIAR SI GUARDA
            }else{  ///SI EL CLIENTE ESTA REPETIDO NO SE GUARDA
                JOptionPane.showMessageDialog(this,"Telefono ya cargado");
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    ///------------VERIFICAR CAMPOS PARA CARGAR UN CLIENTE COMPLETO------------
    private boolean verificarCampos(javax.swing.JTextField tx){
        if(tx.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Completar Campo");
            tx.requestFocus();
            return true;
        }
        return false;
    }
    
    private boolean verificarCamposnum(javax.swing.JTextField tx){
        if(tx.getText().isBlank()||Long.parseLong(tx.getText())<0){   ///VERIFICAR CAMPO VACIO O SI EL NUMERO INGRESADO ES NEGATIVO
            if(tx.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Completar Campo");
            }else{
                JOptionPane.showMessageDialog(this, "No ingresar numeros negativos");
            }
            tx.requestFocus();
            return true;
        }
        return false;
    }
    
    ///------------BOTON NUEVO PARA LIMPIAR------------
    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        limpiar();  ///LIMPIAR DATOS
    }//GEN-LAST:event_jBNuevoActionPerformed

    ///------------BOTON SALIR------------
    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose(); ///CERRAR VENTANA
    }//GEN-LAST:event_jBSalirActionPerformed
    
    ///------------VERIFICAR NUMEROS------------
    private void jTDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDNIKeyTyped
        verificarNum(evt,jTDNI);    ///VERIFICAR DNI
    }//GEN-LAST:event_jTDNIKeyTyped

    private void jTTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTelefonoKeyTyped
        verificarNum(evt,jTTelefono);   ///VERIFICAR TELEFONO
    }//GEN-LAST:event_jTTelefonoKeyTyped
    ///------------VERIFICADOR SOLO NUMEROS------------
    private void verificarNum(java.awt.event.KeyEvent evt,javax.swing.JTextField tx){
        if(Character.isLetter(evt.getKeyChar())||Character.toString(evt.getKeyChar()).matches(" ")){
            JOptionPane.showMessageDialog(this, "No se permiten letras en este campo","Advertencia",JOptionPane.WARNING_MESSAGE);
            evt.consume();
            tx.requestFocus();
        }
    }
    
    ///------------VERIFICAR TEXTO------------
    private void jTApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidoKeyTyped
        verificarChar(evt,jTApellido);  ///VERIFICAR APELLIDO
    }//GEN-LAST:event_jTApellidoKeyTyped

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped
        verificarChar(evt, jTNombre);   ///VERIFICAR NOMBRE
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCiudadKeyTyped
        verificarChar(evt,jTCiudad);    ///VERIFICAR CIUDAD
    }//GEN-LAST:event_jTCiudadKeyTyped
    ///------------VERIFICADOR SOLO TEXTO------------
    private void verificarChar(java.awt.event.KeyEvent evt,javax.swing.JTextField tx){
        if(Character.isDigit(evt.getKeyChar())){
            JOptionPane.showMessageDialog(this, "No se permiten numeros en este campo","Advertencia",JOptionPane.WARNING_MESSAGE);
            evt.consume();
            tx.requestFocus();
        }
    }
    
    ///------------LIMPIAR DATOS------------
    private void limpiar(){
        jTDNI.setText(null);
        jTApellido.setText(null);
        jTNombre.setText(null);
        jTCiudad.setText(null);
        jTDireccion.setText(null);
        jTTelefono.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCiudad;
    private javax.swing.JLabel jLDNI;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTCiudad;
    private javax.swing.JTextField jTDNI;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTTelefono;
    // End of variables declaration//GEN-END:variables
}
